---
swagger: "2.0"
info:
  description: >
    goliac is a golang REST application skeleton
    The base path for all the APIs is "/api/v1".
  title: goliac
  version: 1.0.0
tags:
  - name: health
    description: Check if goliac is healthy
x-tagGroups:
  - name: goliac Management
    tags:
      - app
  - name: Health Check
    tags:
      - health
consumes:
- application/json
produces:
- application/json
schemes:
- http
basePath: "/api/v1"
paths:
  /liveness:
    $ref: ./liveness.yaml
  /readiness:
    $ref: ./readiness.yaml
  /flushcache:
    $ref: ./flushcache.yaml
  /resync:
    $ref: ./resync.yaml
  /status:
    $ref: ./status.yaml


definitions:

  # Health check
  health:
    type: object
    properties:
      status:
        type: string

  # Goliac statistics
  status:
    type: object
    properties:
      lastSyncTime:
        type: string
        minLength: 1
      lastSyncError:
        type: string
      nbUsers:
        type: integer
        x-omitempty: false
      nbUsersExternal:
        type: integer
        x-omitempty: false
      nbTeams:
        type: integer
        x-omitempty: false
      nbRepos:
        type: integer
        x-omitempty: false

  # Default Error
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        minLength: 1
