---
swagger: "2.0"
info:
  description: >
    goliac is a golang REST application skeleton
    The base path for all the APIs is "/api/v1".
  title: goliac
  version: 1.0.0
tags:
  - name: health
    description: Check if goliac is healthy
x-tagGroups:
  - name: goliac Management
    tags:
      - app
  - name: Health Check
    tags:
      - health
consumes:
- application/json
produces:
- application/json
schemes:
- http
basePath: "/api/v1"
paths:
  /liveness:
    $ref: ./liveness.yaml
  /readiness:
    $ref: ./readiness.yaml
  /flushcache:
    $ref: ./flushcache.yaml
  /resync:
    $ref: ./resync.yaml
  /status:
    $ref: ./status.yaml
  /users:
    $ref: ./users.yaml
  /users/{userID}:
    $ref: ./user.yaml

definitions:

  # Health check
  health:
    type: object
    properties:
      status:
        type: string

  # users (org and external)
  users:
    type: object
    properties:
      users:
        type: array
        items:
          $ref: "#/definitions/user"

  user:
    type: object
    properties:
      name:
        type: string
        x-isnullable: false
      external:
        type: boolean
        x-isnullable: false

  userDetails:
    type: object
    properties:
      teams:
        type: array
        items:
          $ref: "#/definitions/team"
      repositories:
        type: array
        items:
          $ref: "#/definitions/repository"

  repository:
    type: object
    properties:
      name:
        type: string
        x-isnullable: false
      public:
        type: boolean
        x-isnullable: false
        x-omitempty: false
      archived:
        type: boolean
        x-isnullable: false
        x-omitempty: false

  team:
    type: object
    properties:
      name:
        type: string
        x-isnullable: false
      owners:
        type: array
        items:
          type: string
          minLength: 1
      members:
        type: array
        items:
          type: string
          minLength: 1

  # Goliac statistics
  status:
    type: object
    properties:
      lastSyncTime:
        type: string
        minLength: 1
      lastSyncError:
        type: string
      nbUsers:
        type: integer
        x-omitempty: false
      nbUsersExternal:
        type: integer
        x-omitempty: false
      nbTeams:
        type: integer
        x-omitempty: false
      nbRepos:
        type: integer
        x-omitempty: false

  # Default Error
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        minLength: 1
